"""empty message

Revision ID: 04282c7198e2
Revises: 6bbdc42d5594
Create Date: 2022-11-04 07:37:48.072726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04282c7198e2'
down_revision = '6bbdc42d5594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
