"""Setup goals model

Revision ID: 077902a4e60d
Revises: a6e7c745333d
Create Date: 2022-11-06 11:20:15.851363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077902a4e60d'
down_revision = 'a6e7c745333d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
