"""empty message

Revision ID: 082481fba230
Revises: 0f19bb1e14be
Create Date: 2022-11-05 21:10:18.368314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '082481fba230'
down_revision = '0f19bb1e14be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
