"""added more variables to the class

Revision ID: 08d90f10bf26
Revises: bddf6ef63637
Create Date: 2022-11-16 23:05:26.972666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d90f10bf26'
down_revision = 'bddf6ef63637'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('goal', sa.Column('description', sa.String(length=80), nullable=True))
    op.add_column('goal', sa.Column('goal_title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_title')
    op.drop_column('goal', 'description')
    op.drop_column('goal', 'completed_at')
    # ### end Alembic commands ###
