"""add relationship

Revision ID: 094aeb2f9038
Revises: 8c390a528cf2
Create Date: 2022-11-07 20:39:35.181342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094aeb2f9038'
down_revision = '8c390a528cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
