"""empty message

Revision ID: 0b7a0c7df07c
Revises: a81f62f52c87
Create Date: 2022-11-02 16:36:16.499492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7a0c7df07c'
down_revision = 'a81f62f52c87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
