"""empty message

Revision ID: 0c0ebdaf2bef
Revises: 747bb3b16826
Create Date: 2022-11-05 16:13:33.340758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0ebdaf2bef'
down_revision = '747bb3b16826'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
