"""Update: edit model

Revision ID: 0fd38416743d
Revises: 10e35f497226
Create Date: 2022-11-10 12:50:01.421243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd38416743d'
down_revision = '10e35f497226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'is_complete')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
