"""empty message

Revision ID: 143607d7509b
Revises: 50e6ba6b2899
Create Date: 2022-11-02 14:09:36.795693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '143607d7509b'
down_revision = '50e6ba6b2899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'task_description')
    op.drop_column('task', 'task_title')
    op.drop_column('task', 'task_completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    op.drop_column('task', 'description')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
