"""empty message

Revision ID: 151bce5b362a
Revises: c6bcf101de17
Create Date: 2022-11-09 13:43:22.748616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '151bce5b362a'
down_revision = 'c6bcf101de17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
