"""empty message

Revision ID: 163be630cc59
Revises: e2e307567cc5
Create Date: 2022-11-08 23:18:28.835413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163be630cc59'
down_revision = 'e2e307567cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
