"""empty message

Revision ID: 17069dd1dc5c
Revises: 08d90f10bf26
Create Date: 2022-11-21 09:59:35.100729

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17069dd1dc5c'
down_revision = '08d90f10bf26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(length=80), nullable=True))
    op.drop_column('goal', 'goal_title')
    op.drop_column('goal', 'completed_at')
    op.drop_column('goal', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('goal', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('goal', sa.Column('goal_title', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
