"""empty message

Revision ID: 185223843d7d
Revises: 014260957d84
Create Date: 2022-11-08 19:26:51.162804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '185223843d7d'
down_revision = '014260957d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
