"""empty message

Revision ID: 19516111b86f
Revises: c675ff831873
Create Date: 2022-11-06 18:59:36.726969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19516111b86f'
down_revision = 'c675ff831873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
