"""empty message

Revision ID: 1bca4bbb7ab8
Revises: 934eb7bb2cdf
Create Date: 2022-11-03 16:56:03.872157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bca4bbb7ab8'
down_revision = '934eb7bb2cdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_is_complete', sa.Boolean(), nullable=False))
    op.drop_column('task', 'task_is_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('task', 'task_is_complete')
    # ### end Alembic commands ###
