"""empty message

Revision ID: 1cd471221364
Revises: 9194d9b92ad2
Create Date: 2022-11-09 09:45:53.578027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1cd471221364'
down_revision = '9194d9b92ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('task', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
