"""empty message

Revision ID: 20af7b695e68
Revises: ef0ef800bc1d
Create Date: 2022-11-07 20:29:05.134359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20af7b695e68'
down_revision = 'ef0ef800bc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
