"""added Goal model

Revision ID: 22738f217482
Revises: cefd41a62161
Create Date: 2022-11-07 10:05:38.575740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22738f217482'
down_revision = 'cefd41a62161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
