"""empty message

Revision ID: 23693f9aede3
Revises: a225b59e0b7b
Create Date: 2022-11-08 22:10:22.467815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23693f9aede3'
down_revision = 'a225b59e0b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
