"""empty message

Revision ID: 23989ab53720
Revises: 0f0cf2dfffb0
Create Date: 2022-11-03 17:22:18.202342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23989ab53720'
down_revision = '0f0cf2dfffb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
