"""added is_complete column as boolean to Task table

Revision ID: 23f7f42ca3eb
Revises: 679f8f6423bd
Create Date: 2022-11-06 12:07:31.825319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23f7f42ca3eb'
down_revision = '679f8f6423bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
