"""empty message

Revision ID: 244dd50038f5
Revises: edbe6a4e10a9
Create Date: 2022-11-07 22:10:05.134300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244dd50038f5'
down_revision = 'edbe6a4e10a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
