"""empty message

Revision ID: 2e8edfc0a7f9
Revises: 778b2946a33b
Create Date: 2022-11-08 19:58:12.336533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8edfc0a7f9'
down_revision = '778b2946a33b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('lazy', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'lazy')
    # ### end Alembic commands ###
