"""empty message

Revision ID: 31602e68d33c
Revises: 274bb3ce7398
Create Date: 2022-11-03 14:10:24.492596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31602e68d33c'
down_revision = '274bb3ce7398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
