"""empty message

Revision ID: 32258db1269b
Revises: e5eff1918c0a
Create Date: 2022-11-10 19:52:03.585756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32258db1269b'
down_revision = 'e5eff1918c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
