"""empty message

Revision ID: 323df1c9b8cd
Revises: ab5e094fe362
Create Date: 2022-11-06 19:22:18.654089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323df1c9b8cd'
down_revision = 'ab5e094fe362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
