"""empty message

Revision ID: 345ce3a3ef6e
Revises: 17c4518a2cc0
Create Date: 2022-11-09 13:09:49.973267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345ce3a3ef6e'
down_revision = '17c4518a2cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
