"""adds is_complete

Revision ID: 417ac9596c00
Revises: 5f1aa3268bad
Create Date: 2022-11-05 09:51:29.520442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417ac9596c00'
down_revision = '5f1aa3268bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('goal_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    op.drop_table('goal')
    # ### end Alembic commands ###
