"""empty message

Revision ID: 418acff5aaa2
Revises: cf32372db3e4
Create Date: 2022-11-09 19:29:11.116983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '418acff5aaa2'
down_revision = 'cf32372db3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
