"""empty message

Revision ID: 44345a24a168
Revises: 62d5118bfe66
Create Date: 2022-11-07 13:46:47.008711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44345a24a168'
down_revision = '62d5118bfe66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
