"""empty message

Revision ID: 460d1ab8abdf
Revises: 
Create Date: 2022-11-04 18:08:29.873861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460d1ab8abdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
