"""empty message

Revision ID: 46841ec82b35
Revises: b5f7666ab7c5
Create Date: 2022-11-09 11:54:28.436860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46841ec82b35'
down_revision = 'b5f7666ab7c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
