"""empty message

Revision ID: 4ea131076bf8
Revises: db4c42ccc3c8
Create Date: 2022-11-08 22:31:24.277704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea131076bf8'
down_revision = 'db4c42ccc3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    # ### end Alembic commands ###
