"""empty message

Revision ID: 51648b56329a
Revises: ead32ddf1ab3
Create Date: 2022-11-09 20:00:47.528199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51648b56329a'
down_revision = 'ead32ddf1ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
