"""empty message

Revision ID: 534faf0643b9
Revises: 77e78f28b255
Create Date: 2022-11-09 21:28:57.876031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534faf0643b9'
down_revision = '77e78f28b255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'lazy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('lazy', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
