"""empty message

Revision ID: 53715d9d2a13
Revises: ee7f06c88029
Create Date: 2022-11-05 22:17:56.163600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53715d9d2a13'
down_revision = 'ee7f06c88029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
