"""adds to create_dict, update, and new_instance_from_dict to goal model

Revision ID: 5e62df716d40
Revises: d2068374c15b
Create Date: 2022-11-08 17:40:58.272320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e62df716d40'
down_revision = 'd2068374c15b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
