"""empty message

Revision ID: 60674edafe1a
Revises: 1bca4bbb7ab8
Create Date: 2022-11-03 17:01:11.041201

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '60674edafe1a'
down_revision = '1bca4bbb7ab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.add_column('task', sa.Column('title', sa.String(), nullable=False))
    op.drop_column('task', 'task_title')
    op.drop_column('task', 'task_description')
    op.drop_column('task', 'task_is_complete')
    op.drop_column('task', 'task_completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_is_complete', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('task', sa.Column('task_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('task_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'title')
    op.drop_column('task', 'is_complete')
    op.drop_column('task', 'description')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
