"""empty message

Revision ID: 6164e690559f
Revises: 32f99ab5f95c
Create Date: 2022-11-06 11:24:49.113348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6164e690559f'
down_revision = '32f99ab5f95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('Completed On', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('Description', sa.String(length=80), nullable=True))
    op.add_column('task', sa.Column('Title', sa.String(length=80), nullable=True))
    op.drop_index('ix_task_completed_at', table_name='task')
    op.drop_index('ix_task_description', table_name='task')
    op.drop_index('ix_task_title', table_name='task')
    op.create_index(op.f('ix_task_Completed On'), 'task', ['Completed On'], unique=False)
    op.create_index(op.f('ix_task_Description'), 'task', ['Description'], unique=False)
    op.create_index(op.f('ix_task_Title'), 'task', ['Title'], unique=False)
    op.drop_column('task', 'description')
    op.drop_column('task', 'title')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_Title'), table_name='task')
    op.drop_index(op.f('ix_task_Description'), table_name='task')
    op.drop_index(op.f('ix_task_Completed On'), table_name='task')
    op.create_index('ix_task_title', 'task', ['title'], unique=False)
    op.create_index('ix_task_description', 'task', ['description'], unique=False)
    op.create_index('ix_task_completed_at', 'task', ['completed_at'], unique=False)
    op.drop_column('task', 'Title')
    op.drop_column('task', 'Description')
    op.drop_column('task', 'Completed On')
    # ### end Alembic commands ###
