"""empty message

Revision ID: 645e8ab5c17d
Revises: 2d9e6bdfd591
Create Date: 2022-11-07 15:14:18.892165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645e8ab5c17d'
down_revision = '2d9e6bdfd591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
