"""renamed primary keys

Revision ID: 6580820c43ac
Revises: 
Create Date: 2022-11-03 17:13:47.914078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6580820c43ac"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "goal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("task_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task")
    op.drop_table("goal")
    # ### end Alembic commands ###
