"""empty message

Revision ID: 6be6d2695365
Revises: 6a380259e60c
Create Date: 2022-11-08 15:30:09.365676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6be6d2695365'
down_revision = '6a380259e60c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'goal_title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal', 'goal_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
