"""empty message

Revision ID: 727074994ae8
Revises: be658fef439f
Create Date: 2022-11-07 20:06:03.383874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727074994ae8'
down_revision = 'be658fef439f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
