"""updated Goal model

Revision ID: 735ec5539917
Revises: 513788d29724
Create Date: 2022-11-09 14:12:52.696034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735ec5539917'
down_revision = '513788d29724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
