"""empty message

Revision ID: 77893fe16680
Revises: 6d401cad3969
Create Date: 2022-11-09 14:54:18.369856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77893fe16680'
down_revision = '6d401cad3969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
