"""empty message

Revision ID: 778b2946a33b
Revises: 7c2c6aa128f7
Create Date: 2022-11-08 19:40:20.729957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778b2946a33b'
down_revision = '7c2c6aa128f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
