"""added is complete attribute with default value of false to task model

Revision ID: 79ddf2f58c1d
Revises: f7a9baaa8c50
Create Date: 2022-11-05 17:42:53.416734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ddf2f58c1d'
down_revision = 'f7a9baaa8c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
