"""empty message

Revision ID: 83475dc44270
Revises: c43a1e0904c1
Create Date: 2022-11-10 02:23:04.287845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83475dc44270'
down_revision = 'c43a1e0904c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.Boolean(), nullable=True))
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###
