"""adds goal model and endpoints

Revision ID: 842057bcc53f
Revises: 60a21ffd758f
Create Date: 2022-11-10 05:51:32.297250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842057bcc53f'
down_revision = '60a21ffd758f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
