"""empty message

Revision ID: 8524b4ed10c8
Revises: 62b67d156b2c
Create Date: 2022-11-12 13:47:31.855945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8524b4ed10c8'
down_revision = '62b67d156b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
