"""Sets up one Goal to many Task relationship

Revision ID: 859c7bc6c281
Revises: 63f482b5543a
Create Date: 2022-11-06 11:16:10.281503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '859c7bc6c281'
down_revision = '63f482b5543a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('one_goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['one_goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'one_goal_id')
    # ### end Alembic commands ###
