"""empty message

Revision ID: 862c9ef7a2c4
Revises: 65fca6b930ff
Create Date: 2022-11-03 21:38:37.939878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862c9ef7a2c4'
down_revision = '65fca6b930ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
