"""empty message

Revision ID: 868af565e7b6
Revises: f37d9768c7d0
Create Date: 2022-11-05 14:54:16.029616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '868af565e7b6'
down_revision = 'f37d9768c7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('task', 'task_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('task', 'id')
    # ### end Alembic commands ###
