"""created new relationship between goal and task

Revision ID: 8a2d4c508923
Revises: 6414136f3bad
Create Date: 2022-11-08 11:14:16.443781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2d4c508923'
down_revision = '6414136f3bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'goal', 'task', ['task_id'], ['id'])
    op.drop_constraint('task_goal_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_goal_id_fkey', 'task', 'goal', ['goal_id'], ['id'])
    op.drop_constraint(None, 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    # ### end Alembic commands ###
