"""empty message

Revision ID: 91d304e19eb9
Revises: 3c161330e9c2
Create Date: 2022-11-03 11:41:03.550166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d304e19eb9'
down_revision = '3c161330e9c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###
