"""empty message

Revision ID: 92987b38df3d
Revises: 339b3ba4c742
Create Date: 2022-11-08 12:58:22.949543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92987b38df3d'
down_revision = '339b3ba4c742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
