"""empty message

Revision ID: 934eb7bb2cdf
Revises: 
Create Date: 2022-11-03 14:19:47.149861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934eb7bb2cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('task',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('task_title', sa.String(), nullable=False),
    sa.Column('task_description', sa.String(), nullable=True),
    sa.Column('task_completed_at', sa.DateTime(), nullable=True),
    sa.Column('task_is_completed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('goal')
    # ### end Alembic commands ###
