"""empty message

Revision ID: 939ead371223
Revises: 85a439c913d5
Create Date: 2022-11-08 18:02:48.674739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939ead371223'
down_revision = '85a439c913d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
