"""empty message

Revision ID: 953442d1f52e
Revises: b68b3c3e351c
Create Date: 2022-11-08 16:13:07.530001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '953442d1f52e'
down_revision = 'b68b3c3e351c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
