"""empty message

Revision ID: 9693aa3773e9
Revises: 5b36a245f83f
Create Date: 2022-11-05 12:40:08.721589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9693aa3773e9'
down_revision = '5b36a245f83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title_id')
    # ### end Alembic commands ###
