"""empty message

Revision ID: 998a9f75c823
Revises: 5551b3415bca
Create Date: 2022-11-03 23:12:04.021538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998a9f75c823'
down_revision = '5551b3415bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
