"""goal attempt 3

Revision ID: 9b90354e2091
Revises: 8a2d4c508923
Create Date: 2022-11-08 11:21:05.822684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b90354e2091'
down_revision = '8a2d4c508923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('goal_task_id_fkey', 'goal', type_='foreignkey')
    op.drop_column('goal', 'task_id')
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    op.add_column('goal', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('goal_task_id_fkey', 'goal', 'task', ['task_id'], ['id'])
    # ### end Alembic commands ###
