"""empty message

Revision ID: a85885fda39a
Revises: 0d1f454e628e
Create Date: 2022-11-06 17:17:40.689451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85885fda39a'
down_revision = '0d1f454e628e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'is_complete',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
