"""POST upgrade

Revision ID: d3fb3e65d61f
Revises: 0519244a449f
Create Date: 2022-11-02 15:56:16.145406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3fb3e65d61f'
down_revision = '0519244a449f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
