"""empty message

Revision ID: da51b29e1234
Revises: e641aaa91219
Create Date: 2022-11-02 14:38:04.100650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da51b29e1234'
down_revision = 'e641aaa91219'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    op.drop_column('task', 'description')
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
