"""empty message

Revision ID: db4c42ccc3c8
Revises: f5b0d5788c85
Create Date: 2022-11-08 21:30:37.136427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4c42ccc3c8'
down_revision = 'f5b0d5788c85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=False)
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.alter_column('task', 'title',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('task', 'description',
               existing_type=sa.VARCHAR(length=280),
               nullable=True)
    op.drop_column('task', 'goal_id')
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
