"""empty message

Revision ID: e17a9723efb9
Revises: 668ac666b731
Create Date: 2022-11-06 09:58:18.698453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17a9723efb9'
down_revision = '668ac666b731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###
