"""empty message

Revision ID: e2edbc442786
Revises: 6be6d2695365
Create Date: 2022-11-08 15:43:58.948808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2edbc442786'
down_revision = '6be6d2695365'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('goal', 'goal_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
