"""empty message

Revision ID: f16f36e470cc
Revises: af54b8a8f686
Create Date: 2022-11-03 11:26:06.188313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f16f36e470cc'
down_revision = 'af54b8a8f686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
