<<<<<<<< HEAD:migrations/versions/e608896720f1_created_database.py
"""created database

Revision ID: e608896720f1
Revises: 
Create Date: 2022-11-10 18:36:49.396800
========
"""changes

Revision ID: f1a692f05e5e
Revises: 
Create Date: 2022-11-09 17:44:00.617128
>>>>>>>> d8e741bd29216bd2bfde8d2f7844a847b1898b34:migrations/versions/f1a692f05e5e_changes.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/e608896720f1_created_database.py
revision = 'e608896720f1'
========
revision = 'f1a692f05e5e'
>>>>>>>> d8e741bd29216bd2bfde8d2f7844a847b1898b34:migrations/versions/f1a692f05e5e_changes.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('goal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('goal')
    # ### end Alembic commands ###
