"""Added a Goal model with id and title attributes

Revision ID: f4e9bb4a99ae
Revises: 143607d7509b
Create Date: 2022-11-09 15:07:30.825612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4e9bb4a99ae'
down_revision = '143607d7509b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'title')
    # ### end Alembic commands ###
