"""empty message

Revision ID: f81eec31fc3f
Revises: cf1d8b0de5b9
Create Date: 2022-11-11 19:07:54.318699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81eec31fc3f'
down_revision = 'cf1d8b0de5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_completed_at', table_name='task')
    op.drop_index('ix_task_description', table_name='task')
    op.drop_index('ix_task_title', table_name='task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_task_title', 'task', ['title'], unique=False)
    op.create_index('ix_task_description', 'task', ['description'], unique=False)
    op.create_index('ix_task_completed_at', 'task', ['completed_at'], unique=False)
    # ### end Alembic commands ###
